### ISSUE TITLE
Cannot read property' filter' of undefined

### ISSUE THREAD

**Issue by zgbjmy2009** [Kruithne/wow.export#276]
runtime.log:
Failed to load CASC: TypeError: Cannot read property 'filter' of undefined
    at Object.initializeItemDisplays (chrome-extension://hjnamambhlpahhgnmkmdplebghbjncpm/src/app.js:1:55404)
    at async Object.loadTables (chrome-extension://hjnamambhlpahhgnmkmdplebghbjncpm/src/app.js:1:60069)
    at async Object.load (chrome-extension://hjnamambhlpahhgnmkmdplebghbjncpm/src/app.js:1:69879)
    at async chrome-extension://hjnamambhlpahhgnmkmdplebghbjncpm/src/app.js:1:190104
    at async Object.block (chrome-extension://hjnamambhlpahhgnmkmdplebghbjncpm/src/app.js:1:18508) {
  [stack]: "TypeError: Cannot read property 'filter' of undefined\n" +
    '    at Object.initializeItemDisplays (chrome-extension://hjnamambhlpahhgnmkmdplebghbjncpm/src/app.js:1:55404)\n' +
    '    at async Object.loadTables (chrome-extension://hjnamambhlpahhgnmkmdplebghbjncpm/src/app.js:1:60069)\n' +
    '    at async Object.load (chrome-extension://hjnamambhlpahhgnmkmdplebghbjncpm/src/app.js:1:69879)\n' +
    '    at async chrome-extension://hjnamambhlpahhgnmkmdplebghbjncpm/src/app.js:1:190104\n' +
    '    at async Object.block (chrome-extension://hjnamambhlpahhgnmkmdplebghbjncpm/src/app.js:1:18508)',
  [message]: "Cannot read property 'filter' of undefined"

what 's mean ? I already set the "Data Table Definition Repository" = "https://www.kruithne.net/wow.export/data/dbd/?def=%s" ,and set CASC Locale both "zhCN" or "zhTW" all with this error . the loading progress in loading " item displays" the show this error.

**Comment by Kruithne** [comment]
Please post your full runtime log file.

**Comment by Kruithne** [comment]
Closing this, re-open if anyone can reproduce

**Comment by zealvurte** [comment]
Had this happen to me today with a new install. @Marlamin's advice didn't solve it.

[runtime.log](https://github.com/Kruithne/wow.export/files/10245859/runtime.log)

**Comment by Marlamin** [comment]
> Had this happen to me today with a new install. @Marlamin's advice didn't solve it.
> 
> [runtime.log](https://github.com/Kruithne/wow.export/files/10245859/runtime.log)

This should already be fixed on master, try again next update
