### ISSUE TITLE
RangeError loading items tab

### ISSUE THREAD

**Issue by Kruithne** [Kruithne/wow.export#327]
```
Uncaught (in promise) RangeError: The value of "offset" is out of range. It must be an integer. Received NaN
    at __node_internal_captureLargerStackTrace (node:internal/errors:484:5)
    at new NodeError (node:internal/errors:393:5)
    at boundsError (node:internal/buffer:80:11)
    at Buffer.readInt8 (node:internal/buffer:424:5)
    at BLTEReader.readInt8 (app.js:232:28)
    at WDCReader.parse (app.js:19191:50)
    at async EventEmitter.<anonymous> (app.js:21456:5)
```

**Comment by Marlamin** [comment]
Fixed in abd149c9b7429ac4482dff34b4bf90e669a6e52e
