### ISSUE TITLE
10.2.5.52432 - Does not open (DB2 issue)

### ISSUE THREAD

**Issue by DJScias** [Kruithne/wow.export#403]
Hello there,

Seems like I can't seem to open the current PTR in wow.export, throws the following error:
```
[02:27:43] Loading listfile for build 57d6c608b7c6050ec5ba0b52927cf8cf
[02:27:43] Listfile for 57d6c608b7c6050ec5ba0b52927cf8cf is cached locally.
[02:27:46] Invalid listfile line (token count): 
[02:27:46] Loading model mapping...
[02:27:46] Loading DB file DBFilesClient/ModelFileData.db2 from CASC
[02:27:46] Loading local CASC file 1337833 (dbfilesclient/modelfiledata.db2)
[02:27:46] Failed to load CASC: Error: Unsupported DB2 type: 893600855
    at Object.parse (chrome-extension://hjnamambhlpahhgnmkmdplebghbjncpm/src/app.js:1:39385)
    at async Object.initializeModelFileData (chrome-extension://hjnamambhlpahhgnmkmdplebghbjncpm/src/app.js:1:47281)
    at async Object.loadTables (chrome-extension://hjnamambhlpahhgnmkmdplebghbjncpm/src/app.js:1:61122)
    at async Object.load (chrome-extension://hjnamambhlpahhgnmkmdplebghbjncpm/src/app.js:1:71295)
    at async chrome-extension://hjnamambhlpahhgnmkmdplebghbjncpm/src/app.js:1:192922
    at async Object.block (chrome-extension://hjnamambhlpahhgnmkmdplebghbjncpm/src/app.js:1:18995) {
  [stack]: 'Error: Unsupported DB2 type: 893600855\n' +
    '    at Object.parse (chrome-extension://hjnamambhlpahhgnmkmdplebghbjncpm/src/app.js:1:39385)\n' +
    '    at async Object.initializeModelFileData (chrome-extension://hjnamambhlpahhgnmkmdplebghbjncpm/src/app.js:1:47281)\n' +
    '    at async Object.loadTables (chrome-extension://hjnamambhlpahhgnmkmdplebghbjncpm/src/app.js:1:61122)\n' +
    '    at async Object.load (chrome-extension://hjnamambhlpahhgnmkmdplebghbjncpm/src/app.js:1:71295)\n' +
    '    at async chrome-extension://hjnamambhlpahhgnmkmdplebghbjncpm/src/app.js:1:192922\n' +
    '    at async Object.block (chrome-extension://hjnamambhlpahhgnmkmdplebghbjncpm/src/app.js:1:18995)',
  [message]: 'Unsupported DB2 type: 893600855'
}
```

I reckon it's related to the new `WDC5` format?

Figured I'd make a bug report all the same, just in case.

**Comment by Marlamin** [comment]
Yup, that's expected, will be fixed in an update at some point (tm).

**Comment by Marlamin** [comment]
This was fixed in the latest update.
